#include<stdio.h>

int main()
{
    long int x,y,z,t,u,v;
    int check=0;
    int count=0;
    long int a,b1,b2,b3,b4;

    for(y=180;y<2000;y++)
    {
        check=0;
        for(x=2;x<y;x++)
        {
            if(y%x==0)
            {
                check=1;
            }
        }
        if(check==0)
        {
            for(z=2;z<y;z++)
            {
                check=0;
                for(x=2;x<z;x++)
                {
                    if(z%x==0)
                    {
                        check=1;
                    }
                }
                if(check==0)
                {
                    for(t=2;t<z;t++)
                    {
                        check=0;
                        for(x=2;x<t;x++)
                        {
                            if(t%x==0)
                            {
                                check=1;
                            }
                        }
                        if(check==0)
                        {
                            for(u=2;u<t;u++)
                            {
                                check=0;
                                for(x=2;x<u;x++)
                                {
                                    if(u%x==0)
                                    {
                                        check=1;
                                    }
                                }
                                if(check==0)
                                {
                                    for(v=2;v<u;v++)
                                    {
                                        check=0;
                                        for(x=2;x<v;x++)
                                        {
                                            if(v%x==0)
                                            {
                                                check=1;
                                            }
                                        }
                                        if(check==0)
                                        {
                                            count=0;
                                            // 1.
                                            for(a=1;a<=y;a=a*10)
                                            {
                                                ;
                                            }
                                            b1=z*a+y;
                                            b2=t*a+y;
                                            b3=u*a+y;
                                            b4=v*a+y;
                                            check=0;
                                            for(x=2;x<b1;x++)
                                            {
                                                if(b1%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b2;x++)
                                            {
                                                if(b2%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b3;x++)
                                            {
                                                if(b3%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b4;x++)
                                            {
                                                if(b4%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            //2.
                                            for(a=1;a<=z;a=a*10)
                                            {
                                                ;
                                            }
                                            b1=y*a+z;
                                            b2=t*a+z;
                                            b3=u*a+z;
                                            b4=v*a+z;
                                            check=0;
                                            for(x=2;x<b1;x++)
                                            {
                                                if(b1%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b2;x++)
                                            {
                                                if(b2%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b3;x++)
                                            {
                                                if(b3%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b4;x++)
                                            {
                                                if(b4%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            //3.
                                            for(a=1;a<=t;a=a*10)
                                            {
                                                ;
                                            }
                                            b1=y*a+t;
                                            b2=z*a+t;
                                            b3=u*a+t;
                                            b4=v*a+t;
                                            check=0;
                                            for(x=2;x<b1;x++)
                                            {
                                                if(b1%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b2;x++)
                                            {
                                                if(b2%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b3;x++)
                                            {
                                                if(b3%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b4;x++)
                                            {
                                                if(b4%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            //4.
                                            for(a=1;a<=u;a=a*10)
                                            {
                                                ;
                                            }
                                            b1=y*a+u;
                                            b2=z*a+u;
                                            b3=t*a+u;
                                            b4=v*a+u;
                                            check=0;
                                            for(x=2;x<b1;x++)
                                            {
                                                if(b1%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b2;x++)
                                            {
                                                if(b2%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b3;x++)
                                            {
                                                if(b3%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b4;x++)
                                            {
                                                if(b4%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            //5.
                                            for(a=1;a<=v;a=a*10)
                                            {
                                                ;
                                            }
                                            b1=y*a+v;
                                            b2=z*a+v;
                                            b3=t*a+v;
                                            b4=u*a+v;
                                            check=0;
                                            for(x=2;x<b1;x++)
                                            {
                                                if(b1%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            check=0;
                                            for(x=2;x<b2;x++)
                                            {
                                                if(b2%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b3;x++)
                                            {
                                                if(b3%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }check=0;
                                            for(x=2;x<b4;x++)
                                            {
                                                if(b4%x==0)
                                                {
                                                    check=1;
                                                }
                                            }
                                            if(check==0)
                                            {
                                                count++;
                                            }
                                            if(count==20)
                                            {
                                                printf("%ld %ld %ld %ld %ld\n",y,z,t,u,v);
                                            }
                                            
                                            if(count>10)
                                            {
                                                printf("%d ",count);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}